### ISSUE TITLE
[BUG] The wake command doesn't refresh the sleep timer if issued while the screen is awake

### ISSUE THREAD

**Issue by ealimonda** [thanksmister/wallpanel-android#285]
If the wake command is issued in order to refresh the wake timeout (tested over MQTT) while the screen is already awake, the command seems to be ignored entirely.

**To Reproduce**

- Start with the display asleep
- Issue the wake command, with a large enough wakeTime value so that the Android display sleep timer won't affect the test (any value larger than the system configured sleep timer is fine - let's assume 180 seconds): `{"wake": true, "wakeTime": 180}`
- After less than the specified wakeTime (i.e. 179 seconds), issue the command again in order to keep the display awake: `{"wake": true, "wakeTime": 180}`
- See that the display goes to sleep after a second instead of after 180 seconds.

**Smartphone (please complete the following information):**
 - Device: Lenovo M10 tablet
 - OS: Android 10
 - Applicaiton version 0.9.5 beta 6 (Play Store).

**Additional notes:**

It's possible to work around it by issuing the command `{"wake": false}` just before re-issuing the wake command, and it is not ignored. That looks like a hack though, and I'd rather avoid it.

I believe this is a regression in version 0.9.5, as in previous versions (before the changes related to screensaver, etc), I was able to extend the wakeTime indefinitely by repeating the wake command just before its expiration. I use this as part of a script to maintain the screen awake through a toggle in Home Assistant (while the switch is toggled is on, every 3599 seconds I issue a `{"wake": "true", "wakeTime": 3600}` command to keep it "permanently" awake and as soon as the switch is toggled off, I issue a `{"wake" ":false"}` command to switch it off immediately.

**Comment by thanksmister** [comment]
This has been addressed.

**Comment by ealimonda** [comment]
This seems to be still a problem (with the same steps to reproduce) in version 0.9.5.beta9 downloaded from the Play Store
